/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_UNIXProcess */

#ifndef _Included_java_lang_UNIXProcess
#define _Included_java_lang_UNIXProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_UNIXProcess
 * Method:    waitForProcessExit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_java_lang_UNIXProcess_waitForProcessExit
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_lang_UNIXProcess
 * Method:    forkAndExec
 * Signature: (I[B[B[BI[BI[B[IZ)I
 */
JNIEXPORT jint JNICALL Java_java_lang_UNIXProcess_forkAndExec
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jbyteArray, jint, jbyteArray, jint, jbyteArray, jintArray, jboolean);

/*
 * Class:     java_lang_UNIXProcess
 * Method:    destroyProcess
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_java_lang_UNIXProcess_destroyProcess
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     java_lang_UNIXProcess
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_lang_UNIXProcess_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
