/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_reflect_Executable */

#ifndef _Included_java_lang_reflect_Executable
#define _Included_java_lang_reflect_Executable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_reflect_Executable
 * Method:    getParameters0
 * Signature: ()[Ljava/lang/reflect/Parameter;
 */
JNIEXPORT jobjectArray JNICALL Java_java_lang_reflect_Executable_getParameters0
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_reflect_Executable
 * Method:    getTypeAnnotationBytes0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_lang_reflect_Executable_getTypeAnnotationBytes0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
