/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_reflect_Field */

#ifndef _Included_java_lang_reflect_Field
#define _Included_java_lang_reflect_Field
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_reflect_Field
 * Method:    getTypeAnnotationBytes0
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_lang_reflect_Field_getTypeAnnotationBytes0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
