/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_ProcessEnvironment */

#ifndef _Included_java_lang_ProcessEnvironment
#define _Included_java_lang_ProcessEnvironment
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_ProcessEnvironment_MIN_NAME_LENGTH
#define java_lang_ProcessEnvironment_MIN_NAME_LENGTH 0L
/*
 * Class:     java_lang_ProcessEnvironment
 * Method:    environ
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_java_lang_ProcessEnvironment_environ
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
