/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_invoke_MethodHandle */

#ifndef _Included_java_lang_invoke_MethodHandle
#define _Included_java_lang_invoke_MethodHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_invoke_MethodHandle
 * Method:    invokeExact
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_invoke_MethodHandle_invokeExact
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     java_lang_invoke_MethodHandle
 * Method:    invoke
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_invoke_MethodHandle_invoke
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     java_lang_invoke_MethodHandle
 * Method:    invokeBasic
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_invoke_MethodHandle_invokeBasic
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     java_lang_invoke_MethodHandle
 * Method:    linkToVirtual
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_invoke_MethodHandle_linkToVirtual
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     java_lang_invoke_MethodHandle
 * Method:    linkToStatic
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_invoke_MethodHandle_linkToStatic
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     java_lang_invoke_MethodHandle
 * Method:    linkToSpecial
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_invoke_MethodHandle_linkToSpecial
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     java_lang_invoke_MethodHandle
 * Method:    linkToInterface
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_invoke_MethodHandle_linkToInterface
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
